<?php

namespace Database\Seeders;

use App\Models\Privilege; // Sesuaikan path model
use App\Models\PrivilegeModel;
use App\Models\Role;      // Sesuaikan path model
use App\Models\RoleModel;
use Illuminate\Database\Seeder;

class RoleAndPrivilegeSeeder extends Seeder
{
    public function run(): void
    {
        // Definisikan peran dan hak aksesnya
        $rolesAndPrivileges = [
            'SUPER_ADMIN' => [
                'name' => 'Super Administrator',
                'privileges' => [
                    'GLOBAL_ACCESS',
                    'PRIVILEGE_MANAGE_VIEW',
                    'ROLE_MANAGE_VIEW',
                    'ROLE_MANAGE_INSERT',
                    'ROLE_MANAGE_UPDATE',
                    'ROLE_MANAGE_DELETE',
                    'ACCOUNT_MANAGE_VIEW',
                    'ACCOUNT_MANAGE_INSERT',
                    'ACCOUNT_MANAGE_UPDATE',
                    'ACCOUNT_MANAGE_DELETE',
                    'OPERATIONAL_CART',
                    'OPERATIONAL_SHIFT',
                    'BUSINESS_MANAGE_VIEW',
                    'BUSINESS_MANAGE_INSERT',
                    'BUSINESS_MANAGE_UPDATE',
                    'BUSINESS_MANAGE_DELETE',
                    'EMPLOYEE_MANAGE_VIEW',
                    'EMPLOYEE_MANAGE_INSERT',
                    'EMPLOYEE_MANAGE_UPDATE',
                    'EMPLOYEE_MANAGE_DELETE',
                    'MEMBER_MANAGE_VIEW',
                    'MEMBER_MANAGE_INSERT',
                    'MEMBER_MANAGE_UPDATE',
                    'MEMBER_MANAGE_DELETE',
                    'CUSTOMER_MANAGE_VIEW',
                    'CUSTOMER_MANAGE_INSERT',
                    'CUSTOMER_MANAGE_UPDATE',
                    'CUSTOMER_MANAGE_DELETE',
                    'CUSTOMER_CATEGORY_MANAGE_VIEW',
                    'CUSTOMER_CATEGORY_MANAGE_INSERT',
                    'CUSTOMER_CATEGORY_MANAGE_UPDATE',
                    'CUSTOMER_CATEGORY_MANAGE_DELETE',
                    'OUTLET_MANAGE_VIEW',
                    'OUTLET_MANAGE_INSERT',
                    'OUTLET_MANAGE_UPDATE',
                    'OUTLET_MANAGE_DELETE',
                    'TAXES_MANAGE_VIEW',
                    'TAXES_MANAGE_INSERT',
                    'TAXES_MANAGE_UPDATE',
                    'TAXES_MANAGE_DELETE',
                    'PRODUCT_CATEGORY_MANAGE_VIEW',
                    'PRODUCT_CATEGORY_MANAGE_INSERT',
                    'PRODUCT_CATEGORY_MANAGE_UPDATE',
                    'PRODUCT_CATEGORY_MANAGE_DELETE',
                    'PRODUCT_MANAGE_VIEW',
                    'PRODUCT_MANAGE_INSERT',
                    'PRODUCT_MANAGE_UPDATE',
                    'PRODUCT_MANAGE_DELETE',
                    'UNIT_MANAGE_VIEW',
                    'UNIT_MANAGE_INSERT',
                    'UNIT_MANAGE_UPDATE',
                    'UNIT_MANAGE_DELETE',
                    'PROMO_MANAGE_VIEW',
                    'PROMO_MANAGE_INSERT',
                    'PROMO_MANAGE_UPDATE',
                    'PROMO_MANAGE_DELETE',
                    'PAYMENT_METHOD_VIEW',
                    'PAYMENT_METHOD_INSERT',
                    'PAYMENT_METHOD_DELETE',
                    'PACKAGE_MANAGE_VIEW',
                    'PACKAGE_MANAGE_INSERT',
                    'PACKAGE_MANAGE_UPDATE',
                    'PACKAGE_MANAGE_DELETE',
                    'BUDGET_PROPOSAL_MANAGE_VIEW',
                    'BUDGET_PROPOSAL_MANAGE_INSERT',
                    'BUDGET_PROPOSAL_MANAGE_UPDATE',
                    'BUDGET_PROPOSAL_MANAGE_DELETE',
                    'ACCOUNT_CHART_MANAGE_VIEW',
                    'ACCOUNT_CHART_MANAGE_INSERT',
                    'ACCOUNT_CHART_MANAGE_UPDATE',
                    'ACCOUNT_CHART_MANAGE_DELETE',
                    'JOURNAL_MANAGE_VIEW',
                    'JOURNAL_MANAGE_INSERT',
                    'JOURNAL_MANAGE_UPDATE',
                    'JOURNAL_MANAGE_DELETE',
                    'JOURNAL_MANAGE_EXPORT',
                    'FINANCE_REPORT_VIEW',
                    'FINANCE_CONSO_REPORT_VIEW',
                    'JOURNAL_ENTRIES_CONSO_VIEW',
                    'FINANCE_SETTING_VIEW',
                    'FINANCE_SETTING_UPDATE',
                    'MANAGE_FINANCE_INVOICE_VIEW',
                    'MANAGE_FINANCE_INVOICE_UPDATE',
                    'MANAGE_FINANCE_INVOICE_INSERT',
                    'MANAGE_FINANCE_CONTACT_VIEW',
                    'MANAGE_FINANCE_CONTACT_UPDATE',
                    'MANAGE_FINANCE_CONTACT_INSERT',
                    'MANAGE_FINANCE_CONTACT_DELETE',
                    'MANAGE_FINANCE_BILL_VIEW',
                    'MANAGE_FINANCE_BILL_UPDATE',
                    'MANAGE_FINANCE_BILL_INSERT',
                    "INVENTORY_CATEGORY_MANAGE_VIEW",
                    "INVENTORY_CATEGORY_MANAGE_INSERT",
                    "INVENTORY_CATEGORY_MANAGE_UPDATE",
                    "INVENTORY_CATEGORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_VIEW",
                    "INVENTORY_MANAGE_INSERT",
                    "INVENTORY_MANAGE_UPDATE",
                    "INVENTORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_STOCK_UPDATE",
                    "SHIFTING_JOURNAL_MANAGE_VIEW",
                    "SHIFTING_JOURNAL_MANAGE_INSERT",
                    "SHIFTING_JOURNAL_MANAGE_UPDATE",
                    "SHIFTING_JOURNAL_MANAGE_DELETE",
                ]
            ],
            'CASHIER' => [
                'name' => 'Kasir',
                'privileges' => [
                    'OPERATIONAL_CART',
                    'OPERATIONAL_SHIFT',
                ]
            ],
            'ADMIN_OPERATIONAL' => [
                'name' => 'Admin Operasional',
                'privileges' => [
                    'MANAGE_PRODUCTS_VIEW',
                    'MANAGE_PRODUCTS_CREATE',
                    'MANAGE_PRODUCTS_UPDATE',
                    'MANAGE_PRODUCTS_DELETE',
                    'BUSINESS_MANAGE_VIEW',
                    'CUSTOMER_MANAGE_VIEW',
                    'CUSTOMER_MANAGE_INSERT',
                    'CUSTOMER_MANAGE_UPDATE',
                    'CUSTOMER_MANAGE_DELETE',
                    'CUSTOMER_CATEGORY_MANAGE_VIEW',
                    'OUTLET_MANAGE_VIEW',
                    'OUTLET_MANAGE_INSERT',
                    'OUTLET_MANAGE_UPDATE',
                    'OUTLET_MANAGE_DELETE',
                    'TAXES_MANAGE_VIEW',
                    'TAXES_MANAGE_INSERT',
                    'TAXES_MANAGE_UPDATE',
                    'TAXES_MANAGE_DELETE',
                    'PRODUCT_CATEGORY_MANAGE_VIEW',
                    'PRODUCT_CATEGORY_MANAGE_INSERT',
                    'PRODUCT_CATEGORY_MANAGE_UPDATE',
                    'PRODUCT_CATEGORY_MANAGE_DELETE',
                    'PRODUCT_MANAGE_VIEW',
                    'PRODUCT_MANAGE_INSERT',
                    'PRODUCT_MANAGE_UPDATE',
                    'PRODUCT_MANAGE_DELETE',
                    'UNIT_MANAGE_VIEW',
                    'PROMO_MANAGE_VIEW',
                    'PROMO_MANAGE_INSERT',
                    'PROMO_MANAGE_UPDATE',
                    'PROMO_MANAGE_DELETE',
                    'PAYMENT_METHOD_VIEW',
                    'PACKAGE_MANAGE_VIEW',
                    'PACKAGE_MANAGE_INSERT',
                    'PACKAGE_MANAGE_UPDATE',
                    'PACKAGE_MANAGE_DELETE',
                    "INVENTORY_CATEGORY_MANAGE_VIEW",
                    "INVENTORY_CATEGORY_MANAGE_INSERT",
                    "INVENTORY_CATEGORY_MANAGE_UPDATE",
                    "INVENTORY_CATEGORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_VIEW",
                    "INVENTORY_MANAGE_INSERT",
                    "INVENTORY_MANAGE_UPDATE",
                    "INVENTORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_STOCK_UPDATE",
                    "SHIFTING_JOURNAL_MANAGE_VIEW",
                    "SHIFTING_JOURNAL_MANAGE_INSERT",
                    "SHIFTING_JOURNAL_MANAGE_UPDATE",
                    "SHIFTING_JOURNAL_MANAGE_DELETE",
                ]
            ],
            'FINANCE' => [
                'name' => 'Keuangan Unit',
                'privileges' => [
                    'BUSINESS_MANAGE_VIEW',
                    'FINANCE_REPORT_VIEW',
                    'JOURNAL_MANAGE_VIEW',
                    'JOURNAL_MANAGE_INSERT',
                    'JOURNAL_MANAGE_UPDATE',
                    'JOURNAL_MANAGE_EXPORT',
                    'ACCOUNT_CHART_MANAGE_VIEW',
                    'ACCOUNT_CHART_MANAGE_INSERT',
                    'ACCOUNT_CHART_MANAGE_UPDATE',
                    'MANAGE_FINANCE_CONTACT_VIEW',
                    'MANAGE_FINANCE_INVOICE_VIEW',
                    'MANAGE_FINANCE_INVOICE_UPDATE',
                    'MANAGE_FINANCE_INVOICE_INSERT',
                    'MANAGE_FINANCE_BILL_VIEW',
                    'MANAGE_FINANCE_BILL_UPDATE',
                    'MANAGE_FINANCE_BILL_INSERT',
                    "SHIFTING_JOURNAL_MANAGE_VIEW",
                    "SHIFTING_JOURNAL_MANAGE_INSERT",
                    "SHIFTING_JOURNAL_MANAGE_UPDATE",
                ]
            ],
            'HEAD_FINANCE' => [
                'name' => 'Kepala Keuangan Unit',
                'privileges' => [
                    'BUSINESS_MANAGE_VIEW',
                    'FINANCE_REPORT_VIEW',
                    'JOURNAL_MANAGE_VIEW',
                    'JOURNAL_MANAGE_INSERT',
                    'JOURNAL_MANAGE_UPDATE',
                    'JOURNAL_MANAGE_DELETE',
                    'JOURNAL_MANAGE_EXPORT',
                    'ACCOUNT_CHART_MANAGE_VIEW',
                    'ACCOUNT_CHART_MANAGE_INSERT',
                    'ACCOUNT_CHART_MANAGE_UPDATE',
                    'ACCOUNT_CHART_MANAGE_DELETE',
                    'FINANCE_SETTING_VIEW',
                    'FINANCE_SETTING_UPDATE',
                    'MANAGE_FINANCE_INVOICE_VIEW',
                    'MANAGE_FINANCE_INVOICE_UPDATE',
                    'MANAGE_FINANCE_INVOICE_INSERT',
                    'MANAGE_FINANCE_CONTACT_VIEW',
                    'MANAGE_FINANCE_CONTACT_UPDATE',
                    'MANAGE_FINANCE_CONTACT_INSERT',
                    'MANAGE_FINANCE_CONTACT_DELETE',
                    'MANAGE_FINANCE_BILL_VIEW',
                    'MANAGE_FINANCE_BILL_UPDATE',
                    'MANAGE_FINANCE_BILL_INSERT',
                    "SHIFTING_JOURNAL_MANAGE_VIEW",
                    "SHIFTING_JOURNAL_MANAGE_INSERT",
                    "SHIFTING_JOURNAL_MANAGE_UPDATE",
                    "SHIFTING_JOURNAL_MANAGE_DELETE",
                ]
            ],
            'HR' => [
                'name' => 'HR Unit',
                'privileges' => [
                    'BUSINESS_MANAGE_VIEW',
                    'ACCOUNT_MANAGE_INSERT',
                    'ACCOUNT_MANAGE_UPDATE',
                    'ACCOUNT_MANAGE_VIEW',
                    'ROLE_MANAGE_VIEW',
                    'EMPLOYEE_MANAGE_VIEW',
                    'EMPLOYEE_MANAGE_INSERT',
                    'EMPLOYEE_MANAGE_UPDATE',
                    "INVENTORY_CATEGORY_MANAGE_VIEW",
                    "INVENTORY_CATEGORY_MANAGE_INSERT",
                    "INVENTORY_CATEGORY_MANAGE_UPDATE",
                    "INVENTORY_CATEGORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_VIEW",
                    "INVENTORY_MANAGE_INSERT",
                    "INVENTORY_MANAGE_UPDATE",
                    "INVENTORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_STOCK_UPDATE",
                ]
            ],
            'HEAD_HR' => [
                'name' => 'Kepala HR Unit',
                'privileges' => [
                    'BUSINESS_MANAGE_VIEW',
                    'ACCOUNT_MANAGE_INSERT',
                    'ACCOUNT_MANAGE_UPDATE',
                    'ACCOUNT_MANAGE_VIEW',
                    'ROLE_MANAGE_VIEW',
                    'EMPLOYEE_MANAGE_VIEW',
                    'EMPLOYEE_MANAGE_INSERT',
                    'EMPLOYEE_MANAGE_UPDATE',
                    'EMPLOYEE_MANAGE_DELETE',
                    "INVENTORY_CATEGORY_MANAGE_VIEW",
                    "INVENTORY_CATEGORY_MANAGE_INSERT",
                    "INVENTORY_CATEGORY_MANAGE_UPDATE",
                    "INVENTORY_CATEGORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_VIEW",
                    "INVENTORY_MANAGE_INSERT",
                    "INVENTORY_MANAGE_UPDATE",
                    "INVENTORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_STOCK_UPDATE",
                ]
            ],
            'MARKETING' => [
                'name' => 'Marketing Unit',
                'privileges' => [
                    'BUSINESS_MANAGE_VIEW',
                    'PRODUCT_CATEGORY_MANAGE_VIEW',
                    'PRODUCT_MANAGE_VIEW',
                    'PROMO_MANAGE_VIEW',
                    'PROMO_MANAGE_INSERT',
                    'PROMO_MANAGE_UPDATE',
                    'PROMO_MANAGE_DELETE',
                    'PACKAGE_MANAGE_VIEW',
                    'PACKAGE_MANAGE_INSERT',
                    'PACKAGE_MANAGE_UPDATE',
                    'PACKAGE_MANAGE_DELETE',
                    "INVENTORY_CATEGORY_MANAGE_VIEW",
                    "INVENTORY_CATEGORY_MANAGE_INSERT",
                    "INVENTORY_CATEGORY_MANAGE_UPDATE",
                    "INVENTORY_CATEGORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_VIEW",
                    "INVENTORY_MANAGE_INSERT",
                    "INVENTORY_MANAGE_UPDATE",
                    "INVENTORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_STOCK_UPDATE",
                ]
            ],
            'WAREHOUSE' => [
                'name' => 'Gudang Unit',
                'privileges' => [
                    'BUSINESS_MANAGE_VIEW',
                    "INVENTORY_CATEGORY_MANAGE_VIEW",
                    "INVENTORY_MANAGE_VIEW",
                    "INVENTORY_MANAGE_UPDATE",
                    "INVENTORY_MANAGE_STOCK_UPDATE",
                ]
            ],
            'HEAD_WAREHOUSE' => [
                'name' => 'Kepala Gudang Unit',
                'privileges' => [
                    'BUSINESS_MANAGE_VIEW',
                    "INVENTORY_CATEGORY_MANAGE_VIEW",
                    "INVENTORY_CATEGORY_MANAGE_INSERT",
                    "INVENTORY_CATEGORY_MANAGE_UPDATE",
                    "INVENTORY_CATEGORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_VIEW",
                    "INVENTORY_MANAGE_INSERT",
                    "INVENTORY_MANAGE_UPDATE",
                    "INVENTORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_STOCK_UPDATE",
                ]
            ],
            'UNIT_HEAD' => [
                'name' => 'Kepala Unit',
                'privileges' => [
                    'PRIVILEGE_MANAGE_VIEW',
                    'ROLE_MANAGE_VIEW',
                    'ACCOUNT_MANAGE_VIEW',
                    'ACCOUNT_MANAGE_INSERT',
                    'ACCOUNT_MANAGE_UPDATE',
                    'ACCOUNT_MANAGE_DELETE',
                    'OPERATIONAL_CART',
                    'OPERATIONAL_SHIFT',
                    'BUSINESS_MANAGE_VIEW',
                    'BUSINESS_MANAGE_UPDATE',
                    'EMPLOYEE_MANAGE_VIEW',
                    'EMPLOYEE_MANAGE_INSERT',
                    'EMPLOYEE_MANAGE_UPDATE',
                    'EMPLOYEE_MANAGE_DELETE',
                    'CUSTOMER_MANAGE_VIEW',
                    'CUSTOMER_MANAGE_INSERT',
                    'CUSTOMER_MANAGE_UPDATE',
                    'CUSTOMER_MANAGE_DELETE',
                    'CUSTOMER_CATEGORY_MANAGE_VIEW',
                    'CUSTOMER_CATEGORY_MANAGE_INSERT',
                    'CUSTOMER_CATEGORY_MANAGE_UPDATE',
                    'CUSTOMER_CATEGORY_MANAGE_DELETE',
                    'OUTLET_MANAGE_VIEW',
                    'OUTLET_MANAGE_INSERT',
                    'OUTLET_MANAGE_UPDATE',
                    'OUTLET_MANAGE_DELETE',
                    'TAXES_MANAGE_VIEW',
                    'TAXES_MANAGE_INSERT',
                    'TAXES_MANAGE_UPDATE',
                    'TAXES_MANAGE_DELETE',
                    'PRODUCT_CATEGORY_MANAGE_VIEW',
                    'PRODUCT_CATEGORY_MANAGE_INSERT',
                    'PRODUCT_CATEGORY_MANAGE_UPDATE',
                    'PRODUCT_CATEGORY_MANAGE_DELETE',
                    'PRODUCT_MANAGE_VIEW',
                    'PRODUCT_MANAGE_INSERT',
                    'PRODUCT_MANAGE_UPDATE',
                    'PRODUCT_MANAGE_DELETE',
                    'UNIT_MANAGE_VIEW',
                    'UNIT_MANAGE_INSERT',
                    'UNIT_MANAGE_UPDATE',
                    'UNIT_MANAGE_DELETE',
                    'PROMO_MANAGE_VIEW',
                    'PROMO_MANAGE_INSERT',
                    'PROMO_MANAGE_UPDATE',
                    'PROMO_MANAGE_DELETE',
                    'PAYMENT_METHOD_VIEW',
                    'PAYMENT_METHOD_INSERT',
                    'PAYMENT_METHOD_DELETE',
                    'PACKAGE_MANAGE_VIEW',
                    'PACKAGE_MANAGE_INSERT',
                    'PACKAGE_MANAGE_UPDATE',
                    'PACKAGE_MANAGE_DELETE',
                    'ACCOUNT_CHART_MANAGE_VIEW',
                    'ACCOUNT_CHART_MANAGE_INSERT',
                    'ACCOUNT_CHART_MANAGE_UPDATE',
                    'ACCOUNT_CHART_MANAGE_DELETE',
                    'JOURNAL_MANAGE_VIEW',
                    'JOURNAL_MANAGE_INSERT',
                    'JOURNAL_MANAGE_UPDATE',
                    'JOURNAL_MANAGE_DELETE',
                    'JOURNAL_MANAGE_EXPORT',
                    'FINANCE_REPORT_VIEW',
                    'FINANCE_SETTING_VIEW',
                    'FINANCE_SETTING_UPDATE',
                    'MANAGE_FINANCE_INVOICE_VIEW',
                    'MANAGE_FINANCE_INVOICE_UPDATE',
                    'MANAGE_FINANCE_INVOICE_INSERT',
                    'MANAGE_FINANCE_CONTACT_VIEW',
                    'MANAGE_FINANCE_CONTACT_UPDATE',
                    'MANAGE_FINANCE_CONTACT_INSERT',
                    'MANAGE_FINANCE_CONTACT_DELETE',
                    'MANAGE_FINANCE_BILL_VIEW',
                    'MANAGE_FINANCE_BILL_UPDATE',
                    'MANAGE_FINANCE_BILL_INSERT',
                    "INVENTORY_CATEGORY_MANAGE_VIEW",
                    "INVENTORY_CATEGORY_MANAGE_INSERT",
                    "INVENTORY_CATEGORY_MANAGE_UPDATE",
                    "INVENTORY_CATEGORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_VIEW",
                    "INVENTORY_MANAGE_INSERT",
                    "INVENTORY_MANAGE_UPDATE",
                    "INVENTORY_MANAGE_DELETE",
                    "INVENTORY_MANAGE_STOCK_UPDATE",
                    "UNIT_APPROVAL",
                    "SHIFTING_JOURNAL_MANAGE_VIEW",
                    "SHIFTING_JOURNAL_MANAGE_INSERT",
                    "SHIFTING_JOURNAL_MANAGE_UPDATE",
                    "SHIFTING_JOURNAL_MANAGE_DELETE",
                ]
            ],
            'FINANCE_GLOBAL' => [
                'name' => 'Finance Global',
                'privileges' => [
                    'GLOBAL_ACCESS',
                    'BUSINESS_MANAGE_VIEW',
                    'ACCOUNT_CHART_MANAGE_VIEW',
                    'JOURNAL_MANAGE_VIEW',
                    'JOURNAL_MANAGE_EXPORT',
                    'FINANCE_REPORT_VIEW',
                    'FINANCE_SETTING_VIEW',
                    'FINANCE_SETTING_UPDATE',
                    'FINANCE_CONSO_REPORT_VIEW',
                    'JOURNAL_ENTRIES_CONSO_VIEW',
                ]
            ],
        ];

        foreach ($rolesAndPrivileges as $roleCode => $roleData) {
            // Buat atau update peran
            $role = RoleModel::updateOrCreate(['code' => $roleCode], ['name' => $roleData['name']]);

            // Dapatkan ID dari privilege yang relevan
            $privilegeIds = PrivilegeModel::whereIn('code', $roleData['privileges'])->pluck('id');

            // Sinkronkan relasi di tabel pivot
            $role->rolePrivilege()->sync($privilegeIds);
        }
    }
}
